name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: dtolnay/rust-toolchain@stable
        with: { components: clippy,rustfmt }
      - run: python -m pip install --upgrade pip && pip install -e .
      - run: make ci
